### ISSUE TITLE
Using a ValidateConnectFunc with a context different from context.Background() fails

### ISSUE THREAD

**Issue by oliverbestmann** [jackc/pgconn#40]
In https://github.com/jackc/pgconn/blob/master/pgconn.go#L227 Watch() is called. Then a few lines futher down (https://github.com/jackc/pgconn/blob/master/pgconn.go#L291) the `ValidateConnectFunc` is called. If you pass `target_session_attrs=read-write` to your connection string, this will lead for https://github.com/jackc/pgconn/blob/master/config.go#L707 to be executed, which in turn calls `ExecParams`, `execExtendedPrefix` and then `Watch()` again. If you are passing a non `Background()` context to `Connect()`, this will fail. See stacktrace:

```panic: Watch already in progress
goroutine 1 [running]:
github.com/jackc/pgconn/internal/ctxwatch.(*ContextWatcher).Watch(0xc000db45a0, 0x148e560, 0xc000db2240)
	/go/pkg/mod/github.com/jackc/pgconn@v1.5.0/internal/ctxwatch/context_watcher.go:33 +0xb7
github.com/jackc/pgconn.(*PgConn).execExtendedPrefix(0xc000ea7760, 0x148e560, 0xc000db2240, 0x0, 0x0, 0x0, 0xc00123f798)
	/go/pkg/mod/github.com/jackc/pgconn@v1.5.0/pgconn.go:957 +0x3af
github.com/jackc/pgconn.(*PgConn).ExecParams(0xc000ea7760, 0x148e560, 0xc000db2240, 0x12bc165, 0x1a, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/jackc/pgconn@v1.5.0/pgconn.go:888 +0x81
github.com/jackc/pgconn.ValidateConnectTargetSessionAttrsReadWrite(0x148e560, 0xc000db2240, 0xc000ea7760, 0x0, 0x0)
	/go/pkg/mod/github.com/jackc/pgconn@v1.5.0/config.go:682 +0xaa
github.com/jackc/pgconn.connect(0x148e560, 0xc000db2240, 0xc000de00e0, 0xc001263f00, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/jackc/pgconn@v1.5.0/pgconn.go:285 +0x8ad
github.com/jackc/pgconn.ConnectConfig(0x148e560, 0xc000db2240, 0xc000de00e0, 0x1dbf400, 0x40eb00, 0xc000db4160)
	/go/pkg/mod/github.com/jackc/pgconn@v1.5.0/pgconn.go:139 +0x224
github.com/jackc/pgx/v4.connect(0x148e560, 0xc000db2240, 0xc000de0000, 0x0, 0x0, 0x40f448)
	/go/pkg/mod/github.com/jackc/pgx/v4@v4.6.0/conn.go:198 +0x161
github.com/jackc/pgx/v4.ConnectConfig(...)
	/go/pkg/mod/github.com/jackc/pgx/v4@v4.6.0/conn.go:105
github.com/jackc/pgx/v4/stdlib.(*driverConnector).Connect(0xc000db4160, 0x148e560, 0xc000db2240, 0x148e560, 0xc000db2240, 0xc000da82f0, 0xc00082b860)
	/go/pkg/mod/github.com/jackc/pgx/v4@v4.6.0/stdlib/sql.go:177 +0xbb
github.com/jackc/pgx/v4/stdlib.(*Driver).Open(0xc00071f660, 0x7ffe29c35db7, 0xc1, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/jackc/pgx/v4@v4.6.0/stdlib/sql.go:136 +0xff
github.com/gchaincl/sqlhooks.(*Driver).Open(0xc00069a400, 0x7ffe29c35db7, 0xc1, 0x0, 0x0, 0x40eb00, 0xc000da0000)
	/go/pkg/mod/github.com/gchaincl/sqlhooks@v1.3.0/sqlhooks.go:47 +0x4e
database/sql.dsnConnector.Connect(...)
	/usr/local/go/src/database/sql/sql.go:688
database/sql.(*DB).conn(0xc0003560c0, 0x148e520, 0xc0000aa000, 0xc00082bb01, 0x9ac415, 0x1294180, 0xc000da6420)
	/usr/local/go/src/database/sql/sql.go:1228 +0x201
database/sql.(*DB).PingContext(0xc0003560c0, 0x148e520, 0xc0000aa000, 0xc1, 0xc000da6420)
	/usr/local/go/src/database/sql/sql.go:782 +0x90
database/sql.(*DB).Ping(...)
	/usr/local/go/src/database/sql/sql.go:800```

**Comment by matlockx** [comment]
can be reproduced with test TestConnectWithValidateConnectTargetSessionAttrsReadWrite:
just use `context.WithCancel(context.Background())` as context at https://github.com/jackc/pgconn/blob/master/pgconn_test.go#L349

**Comment by jackc** [comment]
Good catch. Fixed.

**Comment by matlockx** [comment]
may i ask for a release please?
