### ISSUE TITLE
Panice in `parseDSNSettings`

### ISSUE THREAD

**Issue by aeneasr** [jackc/pgconn#47]
Given a DSN of `host= user= password= port= database`, pgconn will throw a panic:

```
panic: runtime error: index out of range [0] with length 0 goroutine 1 [running]: 

github.com/jackc/pgconn.parseDSNSettings(0xc0000a23dc, 0x9, 0xd, 0x0, 0x0) 
/go/pkg/mod/github.com/jackc/pgconn@v1.6.3/config.go:500 +0x6ef 

github.com/jackc/pgconn.ParseConfig(0xc0000a23c0, 0x25, 0x20300000000000, 0x3e97331fffff, 0x0) 
/go/pkg/mod/github.com/jackc/pgconn@v1.6.3/config.go:205 +0x205e 

github.com/jackc/pgx/v4.ParseConfig(0xc0000a23c0, 0x25, 0xc0000a23c0, 0x25, 0x18eec60) /go/pkg/mod/github.com/jackc/pgx/v4@v4.8.0/conn.go:135 +0x4d

github.com/jackc/pgx/v4/stdlib.(*driverConnector).Connect(0xc00009e5e0, 0x147b840, 0xc0000a6010, 0xb8, 0x203000, 0x203000, 0x203000) /go/pkg/mod/github.com/jackc/pgx/v4@v4.8.0/stdlib/sql.go:218 +0x1f5

database/sql.(*DB).conn(0xc0001100c0, 0x147b840, 0xc0000a6010, 0xc0000f1601, 0x9a9af5, 0xb02ec0, 0xc000089710) /usr/local/go/src/database/sql/sql.go:1233 +0x201

database/sql.(*DB).PingContext(0xc0001100c0, 0x147b840, 0xc0000a6010, 0x25, 0xc000089710) /usr/local/go/src/database/sql/sql.go:801 +0x90

database/sql.(*DB).Ping(...) /usr/local/go/src/database/sql/sql.go:819
```

**Comment by jackc** [comment]
> Given a DSN of `host= user= password= port= database`, pgconn will throw a panic:

I assume you mean a DSN of `host= user= password= port= database=`? As without the trailing `=` there is no panic.

I've fixed this in the sense that it no longer panics. But it's still a bad DSN. A DSN with empty non-quoted values doesn't do what you probably want. e.g. That DSN treats the host as `user=`. But this does match the behavior of `psql` / `libpq`.

```
jack@glados ~/dev/pgx ±master⚡ » psql 'host= user= password= port= dbname='                                                                                                                                                            2 ↵
psql: error: could not connect to server: could not translate host name "user=" to address: nodename nor servname provided, or not known
```

**Comment by aeneasr** [comment]
Yup sorry that was a c/p error. Thank you for the quick resolve! I agree that it's a bad DSN and resolving the panic is the appropriate resolution :)
